---
title: "Assignment1_Mar30"
author: "Garrett Bullivant"
date: "2023-03-30"
output:
  html_document: default
  pdf_document: default
---

```{r}
# load relevant libraries 
library(ggplot2)
library(socviz)
library(ggthemes)
library(ggrepel)
library(tidyverse)
```

```{r}
election |> select(state, total_vote, 
                   r_points, pct_trump, party, census) |>
sample_n(5)
```

```{r}
# create a colour palette
party_colors <- c("#2E74C0", "#CB454A")

# establish ggplot for election data in DC state
p0 <- ggplot(data = subset(election, st %nin% "DC"), mapping = aes(x = r_points, y = reorder(state, r_points), color = party))

# add our data points and an intercept line
p1 <- p0 + geom_vline(xintercept = 0, color = "gray30") + geom_point(size = 2)

# add our colour palette to data points
p2 <- p1 + scale_color_manual(values = party_colors)

# fix x-axis
p3 <- p2 + scale_x_continuous(breaks = c( 30, 20, 10, 0, 10, 20, 30, 40), labels = c("30 n (Clinton)", "20", "10", "0", "10", "20", "30", "40\n(Trump)"))

# use facet wrap to split data 
p3 + facet_wrap(~ census, ncol=1, scales="free_y") + 
  guides(color=FALSE) + 
  labs(x = "Point Margin", y = "") +
  theme(axis.text=element_text(size=8))
```


```{r}
# install and preview maps
#install.packages("maps")
library(maps)
us_states <- map_data("state")
head(us_states)
```
```{r}
# make a map
p <- ggplot(data = us_states, mapping = aes(x = long, y = lat, group = group))

p + geom_polygon(fill = "white", color = "black")
```
```{r}
# add colour
p <- ggplot(data = us_states, 
            mapping = aes(x = long, y = lat, group = group, fill = region))
p + geom_polygon(color = 'gray90', linewidth = 0.1) + guides(fill = FALSE)
```
```{r}
#changing map projection
p + geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)+ 
  guides(fill = FALSE)
```

```{r}
# adding data to our map
election$region <- tolower(election$state)
us_states_elec <- left_join(us_states, election, by = 'region')

p0 <- ggplot(data = us_states_elec, mapping = aes(x = long, y = lat, group = group, fill = party))

p1 <- p0 + geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)

p2 <- p1 + scale_fill_manual(values = party_colors) +
  labs(title = "Election Results 2016", fill = NULL)

p2 + theme_map()
```

```{r}
# explore county datasets from socviz
county_map |> sample_n(5)
county_data |> select(id, name, state, pop_dens) |> sample_n(5)
```

```{r}
# merge county map with county data
county_full <- left_join(county_map, county_data, by = "id")

# plotting population density

p <- ggplot(data = county_full, mapping = aes(x = long, y = lat, fill = pop_dens, group = group))

p1 <- p + geom_polygon(color = "gray90", size = 0.05) +
  coord_equal()

p2 <- p1 + scale_fill_brewer(palette="Blues", labels = c("0-10",
"10-50", "50-100", "100-500", "500-1,000", "1,000-5,000", ">5,000"))

p2 + labs(fill = "Population per nsquare mile") +
  theme_map() +
  guides(fill = guide_legend(nrow = 1)) +
  theme(legend.position = "bottom")
```
```{r}
# flow charts in R
#install.packages("DiagrammeR")
library(DiagrammeR)

# make basic flow chart
p0 <- grViz(diagram = "digraph flowchart {
  node [fontname = arial, shape = oval] # 'NODE' defines our nodes' appearance
  tab1 [label = '@@1'] # define how many nodes
  tab2 [label = '@@2']
  tab3 [label = '@@3']
  tab1 -> tab2 -> tab3; #define connections between nodes
}

  [1]: 'Artefact collection in field' #define text of nodes
  [2]: 'Preliminary dating of artefacts (visual)'
  [3]: 'Artefacts sent to lab for dating'
  ")

p0
```

